### ISSUE TITLE
GPU builds?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/nvidia-apex-feedstock#1]
Does this need GPU builds as well?

**Comment by oblute** [comment]
@jakirkham i am unsure - to my knowledge, conda-forge doesn't have GPU testing capabilities right now so i'm not sure how we would test to know if it needed separate building. thoughts?

**Comment by jakirkham** [comment]
My question was motivated by seeing CUDA code in the repo. Though I admit I don't know this code well and can't say how it is used. Was hoping you might know. 🙂

We are able to perform GPU builds. This amounts to requiring `{{ compiler('cuda') }}` in `build` (along with the other compilers) and [re-rendering]( https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-rerender ) the recipe.

Testing infrastructure is still in progress.

**Comment by jakirkham** [comment]
Looking a bit closer, I think that it would make sense to have both a CPU and a GPU build of this package. We have an analogous case with the [UCX feedstock]( https://github.com/conda-forge/ucx-split-feedstock ). Can walk you through how to set this up.

**Comment by oblute** [comment]
@jakirkham okay, appreciate the help! would the method used in that feedstock be preferred over creating two separate packages like tensorflow does? would definitely appreciate some direction/guidance on crafting it like UCX.

**Comment by oblute** [comment]
This was remedied in https://github.com/conda-forge/nvidia-apex-feedstock/pull/2 , so closing this issue.
